import React from 'react';
import Head from 'next/head';
import Navbar from '@/components/Navbar';
import { PostsList } from '@/components/PostsList';
import AddPostForm from '@/components/AddPostForm';
import { NextPage } from 'next';

const Home: NextPage = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>Redux Essentials Example Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <AddPostForm />
      <PostsList />
    </>
  );
};

export default Home;
