import React from 'react'
import Head from 'next/head'
import { useAppSelector } from '@/redux/app/hooks'
import Navbar from '@/components/Navbar'

export default function Home() {
  const posts = useAppSelector(state => state.posts)

  const renderedPosts = posts.map(post => (
    <article className="post-excerpt" key={post.id}>
      <h3>{post.title}</h3>
      <p className="post-content">{post.content.substring(0, 100)}</p>
    </article>

  ))  
  
  return (
    <>
      <Head>
        <title>Redux Essentials Example Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <section className="posts-list">
        <h2>Posts</h2>
        {renderedPosts}
      </section>
    </>
  )
}
